version: '2'
services:
    thymleafgulp-app:
        image: thymleafgulp
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://thymleafgulp-mysql:3306/thymleafgulp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://thymleafgulp-elasticsearch:9200
        ports:
            - 8080:8080
    thymleafgulp-mysql:
        extends:
            file: mysql.yml
            service: thymleafgulp-mysql
    thymleafgulp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: thymleafgulp-elasticsearch
